version: "3"

services:
  collector:
    image: node:18-alpine
    container_name: collector
    ports:
      - "8090:8090"
    volumes:
      # Wir sichern die Daten auf dem Server
      - /opt/stacks/collector_data:/app/data
    # Befehl bereinigt eventuelle npm-Sperren und startet direkt im aktuellen Ordner
    command: sh -c "rm -rf package-lock.json node_modules && npm install express multer sqlite3 && node server.js"
    restart: unless-stopped
